```typescript
export const Strings = {
  app: {
    name: 'Team Segeltorp',
  },
  dashboard: {
    title: 'Team Segeltorp',
    welcome: 'Välkommen till Team Segeltorp',
  },
  common: {
    new: 'Ny',
    used: 'Begagnad',
    total: 'Totalt',
    cars: 'bilar',
    sales: 'Försäljning',
    testDrives: 'Provkörningar',
    statistics: 'Statistik',
    leaderboard: 'Topplista',
    chat: 'Chatt',
    reports: 'Rapporter',
    save: 'Spara',
    cancel: 'Avbryt',
    select: 'Välj',
    loading: 'Laddar...',
    error: 'Ett fel uppstod',
    success: 'Klart!',
    week: 'Vecka',
    month: 'Månad',
    custom: 'Anpassad',
    startDate: 'Startdatum',
    endDate: 'Slutdatum',
  },
  reports: {
    dateRange: 'Välj period',
    selectDateRange: 'Välj datum',
    includeInReport: 'Inkludera i rapport',
    salesOverview: 'Försäljningsöversikt',
    salesByBrand: 'Försäljning per märke',
    testDrives: 'Provkörningar',
    salesPerformance: 'Säljarprestationer',
    generate: 'Generera rapport',
    weeklyOverview: 'Veckovis översikt',
    weekendSales: 'Helgförsäljning',
  },
  sales: {
    newSale: 'Ny försäljning',
    carType: 'Biltyp',
    brand: 'Märke',
    model: 'Modell',
    value: 'Värde',
  },
  testDrive: {
    newTestDrive: 'Ny provkörning',
    upcoming: 'Kommande provkörningar',
    completed: 'Genomförda provkörningar',
    customer: 'Kund',
    phone: 'Telefon',
    date: 'Datum',
    notes: 'Anteckningar',
  },
  notifications: {
    newSale: 'Ny försäljning',
    newTestDrive: 'Ny provkörning',
    goalReached: 'Mål uppnått',
    weeklyReport: 'Veckans rapport',
  },
};
```
